version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: remedios-db
    environment:
      POSTGRES_DB: remedios
      POSTGRES_USER: remedios
      POSTGRES_PASSWORD: remedios123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
